name: Build and Test Only

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  DOTNET_VERSION: '8.0.x'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Test
      run: dotnet test --configuration Release --logger trx --verbosity normal

    - name: Publish API
      run: dotnet publish src/Spe.Bff.Api/Spe.Bff.Api.csproj -c Release -o ./publish

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: spe-api-build
        path: ./publish